<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b89a8365-054a-4aea-95a7-d2b9bc1f70ef</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
    <PackageReference Include="FastEndpoints.Security" Version="8.3.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.3.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Books Module/RiverBooks.Books/RiverBooks.Books.csproj" />
    <ProjectReference Include="../OrderProcessing Module/RiverBooks.OrderProcessing/RiverBooks.OrderProcessing.csproj" />
    <ProjectReference Include="../Users Module/RiverBooks.Users/RiverBooks.Users.csproj" />
  </ItemGroup>

</Project>
